<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="inertial_macros.xacro"/>
    <xacro:include filename="mecanum_wheel_macro.xacro"/>

    <!-- MATERIALS -->

    <material name="yellow">
        <color rgba="1 1 0 1"/>
    </material>

     <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="grey">
        <color rgba="0.5 0.5 0.5 1"/>
    </material>


    <!-- CONSTANS -->
    <xacro:property name="PI" value="3.1415926535897931" />

    <xacro:property name="chassis_length" value="0.4"/>
    <xacro:property name="chassis_width" value="0.24"/>
    <xacro:property name="chassis_height" value="0.1"/>

    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="chassis_offset" value="0.1"/>

    <xacro:property name="wheel_radius" value="0.3"/>
<!--    <xacro:property name="wheel_thickness" value="0.026"/>-->

    <xacro:property name="wheel_offset_x" value="0.125"/>



    <!-- BASE LINK -->

    <link name="base_link">
    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>

    <!-- CHASSIS -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 0"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="0 0 ${chassis_offset}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="yellow"/>
        </visual>

        <collision>
            <origin xyz="0 0 ${chassis_offset}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0 ${chassis_offset}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Yellow</material>
    </gazebo>



        <!--    1) LEFT FRONT WHEEL-->

 <xacro:mecanum_wheel name="left_front" side="-1" interface="hardware_interface/EffortJointInterface" />

  <joint name="left_front_wheel_joint" type="continuous">
    <parent link="chassis" />
    <child link="left_front_wheel_link" />
    <origin rpy="0 0 ${PI/2}"  xyz="${wheel_offset_x} ${wheel_radius/2} 0.1"/>
  </joint>

    <!--    2) LEFT REAR WHEEL-->

 <xacro:mecanum_wheel name="left_rear" side="1" interface="hardware_interface/EffortJointInterface" />

  <joint name="left_rear_wheel_joint" type="continuous">
    <parent link="chassis" />
    <child link="left_rear_wheel_link" />
    <origin rpy="0 0 ${PI/2}"  xyz="${-wheel_offset_x} ${wheel_radius/2} ${chassis_offset}"/>
  </joint>

            <!--    3) RIGHT FRONT WHEEL-->

 <xacro:mecanum_wheel name="right_front" side="1" interface="hardware_interface/EffortJointInterface" />

  <joint name="right_front_wheel_joint" type="continuous">
    <parent link="chassis" />
    <child link="right_front_wheel_link" />
    <origin rpy="0 0 ${PI/2}"  xyz="${wheel_offset_x} ${-wheel_radius/2} ${chassis_offset}"/>
  </joint>


    <!--    4) RIGHT REAR WHEEL-->

 <xacro:mecanum_wheel name="right_rear" side="-1" interface="hardware_interface/EffortJointInterface" />

  <joint name="right_rear_wheel_joint" type="continuous">
    <parent link="chassis" />
    <child link="right_rear_wheel_link" />
    <origin rpy="0 0 ${PI/2}"  xyz="${-wheel_offset_x} ${-wheel_radius/2} ${chassis_offset}"/>
  </joint>





<!--    LIDAR THINGS-->
    <xacro:property name="lidar_offset_z" value="0.15"/>
    <xacro:property name="lidar_offset_x" value="0.1"/>
    <xacro:property name="lidar_base_prop" value="0.1"/>

    <joint name="lidar_joint" type="fixed">
        <parent link="chassis" />
    <child link="lidar_base" />
        <origin xyz="${lidar_offset_x} 0 ${lidar_offset_z}"/>
    </joint>

       <link name="lidar_base">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${lidar_base_prop} ${lidar_base_prop} ${lidar_base_prop}"/>
            </geometry>
            <material name="yellow"/>
        </visual>

        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${lidar_base_prop} ${lidar_base_prop} ${lidar_base_prop}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass/5}" x="${lidar_base_prop}" y="${lidar_base_prop}" z="${lidar_base_prop}">
            <origin xyz="0 0 ${chassis_offset}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="lidar_base">
        <material>Gazebo/Yellow</material>
    </gazebo>



<!--    Odometry publishing-->
     <gazebo>
        <plugin name="libgazebo_ros_p3d" filename="libgazebo_ros_p3d.so">
            <frame_name>map</frame_name>
            <body_name>base_link</body_name>
            <update_rate>30.0</update_rate>
            <gaussian_noise>0.01</gaussian_noise>
        </plugin>
      </gazebo>

 </robot>


<!--    <gazebo>-->
<!--      <plugin name="gazebo_ros_mecanum_diff_drive" filename="libgazebo_ros_mecanum_diff_drive.so">-->
<!--        <commandTopic>cmd_vel</commandTopic>-->
<!--        <odometryTopic>odom</odometryTopic>-->
<!--        <odometryFrame>odom</odometryFrame>-->
<!--        <robotBaseFrame>base_link</robotBaseFrame>-->
<!--        <LeftRear>left_rear_wheel_joint</LeftRear>-->
<!--        <LeftFront>left_front_wheel_joint</LeftFront>-->
<!--        <RightFront>right_front_wheel_joint</RightFront>-->
<!--        <RightRear>right_rear_wheel_joint</RightRear>-->
<!--        <odometryRate>20</odometryRate>-->
<!--        <publishWheelTF>true</publishWheelTF>-->
<!--        <publishWheelJointState>true</publishWheelJointState>-->
<!--        <WheelTorque>1</WheelTorque>-->
<!--        <WheelSeparationW>0.5</WheelSeparationW>-->
<!--        <WheelSeparationL>0.6</WheelSeparationL>-->
<!--        <wheelAccel>5</wheelAccel>-->
<!--        <wheelDiameter>0.13</wheelDiameter>-->
<!--        <publishOdom>true</publishOdom>-->
<!--        <isRollerModel>true</isRollerModel>-->
<!--      </plugin>-->
<!--</gazebo>-->