#joint_state_controller:
#  type: "joint_state_controller/JointStateController"
#  publish_rate: 50
#
#right_front_controller:
#  type: effort_controllers/JointVelocityController
#  joint: right_front_wheel_joint
#  pid: {p: 10.0, i: 0.01, d: 0.0}
#
#left_front_controller:
#  type: effort_controllers/JointVelocityController
#  joint: left_front_wheel_joint
#  pid: {p: 10.0, i: 0.01, d: 0.0}
#
#right_rear_controller:
#  type: effort_controllers/JointVelocityController
#  joint: right_rear_wheel_joint
#  pid: {p: 10.0, i: 0.01, d: 0.0}
#
#left_rear_controller:
#  type: effort_controllers/JointVelocityController
#  joint: left_rear_wheel_joint
#  pid: {p: 10.0, i: 0.01, d: 0.0}
